[project]
name = "frame-fm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hydra-core>=1.3.2",
    "ipykernel>=7.1.0",
    "ipympl>=0.10.0",
    "ipywidgets>=8.1.8",
    "mlflow>=3.6.0",
    "pytorch-lightning>=2.6.0",
    "tensorboard>=2.20.0",
    "timm>=1.0.24",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
