# @package _global_

defaults:
  - config

# Override data settings for Croissant
data:
  jsonld: "Bella_626_R_867f_70c9_33ec.jsonld"
  record_set: "dataRecordSet"
  batch_size: 32
  num_workers: 0

# Override model settings for Regression
model:
  model: "simple_regression"
  learning_rate: 0.001
  input_dim: 2 # Pressure and Salinity
  output_dim: 1 # Temperature

# Override experiment name
mlflow:
  experiment_name: "croissant_tfds_regression"
  run_name: "tfds_croissant_run"
