# configs/model/DEMO-AE-EuroSAT100-FullSpectrum-S.yaml
_target_: FRAME_FM.models.demo_autoencoder.EuroSATAutoencoder

# Architecture
in_channels: 3          # RGB Bands
base_ch: 32              # renamed from base_channels
k_size: 5                # kernel size (default was 5)
latent_dim: 256

# Optimisation hyperparameters
lr: 1e-3



