# configs/config.yaml
defaults:
  - data: eurosat
  - model: EuroSATConvAE
  - trainer: default
  - logging: mlflow
  - _self_

seed: 42

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true