# configs/config.yaml
defaults:
  - data: demo_data
  - model: demo_model
  - trainer: default
  - logging: demo_log
  - _self_

seed: 42

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true