# configs/FRAME_FM_DEMO.yml
# FRAME-FM Demo Config
# This is a config file that represents an MVP for FRAME-FM. 

defaults:
  - data: MVP_EuroSAT100
  - model: DEMO-AE-EuroSAT100-FullSpectrum-S.yaml
  - trainer: DEMO-Trainer.yaml
  - logging: DEMO-mlflow_EuroSAT100.yaml
  - _self_

seed: 42
run_test: true  # flag for evaluating on test set after training

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true