# configs/logging/demo_log.yaml
_target_: FRAME_FM.training.logging_utils.create_mlflow_logger

experiment_name: "frame-fm-demo"
tracking_uri: ${env:MLFLOW_TRACKING_URI, "file:./mlruns"}
run_name: "demo_autoencoder"

tags:
  project: "FRAME-FM"
  dataset: "EuroSAT"
  model: "EuroSAT Autoencoder"
