name: Build Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: astral-sh/setup-uv@v7.2.0        

      - name: Install Dependencies
        run: |          
          uv sync --extra docs

      - name: Clean Python Cache and Docs Artifacts
        run: |
          find . -name '__pycache__' -type d -exec rm -r {} +
          find . -name '*.pyc' -delete
          rm -rf docs/_build/
          rm -rf docs/api/
          ls . 

      - name: Build Documentation
        run: |
          uv run sphinx-build -b html docs/ docs/_build/html/

      - name: Ensure Static Files Are Present
        run: |
          ls -p docs/_build/html/

      - name: Disable Jekyll Processing
        run: touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the root of gh-pages
          folder: docs/_build/html  # Ensure this points to the html folder
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true  # Deletes old files before deployment